const C = @cImport({
    @cDefine("XED_AVX", "1");
    @cDefine("XED_SUPPORTS_LZCNT_TZCNT", "1");
    @cDefine("XED_AMD_ENABLED", "1");
    @cDefine("XED_VIA_ENABLED", "1");
    @cDefine("XED_SUPPORTS_AVX512", "1");
    @cDefine("XED_MPX", "1");
    @cDefine("XED_CET", "1");
    @cDefine("XED_APX", "1");
    @cDefine("XED_SUPPORTS_SHA", "1");
    @cDefine("XED_DECODER", "1");
    @cDefine("XED_ENCODER", "1");

    @cInclude("xed-agen.h");
    @cInclude("xed-attributes.h");
    @cInclude("xed-chip-features.h");
    @cInclude("xed-common-defs.h");
    @cInclude("xed-common-hdrs.h");
    @cInclude("xed-cpuid-rec.h");
    @cInclude("xed-decode.h");
    @cInclude("xed-decoded-inst-api.h");
    @cInclude("xed-decoded-inst.h");
    @cInclude("xed-disas.h");
    @cInclude("xed-encode-check.h");
    @cInclude("xed-encode-direct.h");
    @cInclude("xed-encode.h");
    @cInclude("xed-encoder-hl.h");
    @cInclude("xed-flags.h");
    @cInclude("xed-format-options.h");
    @cInclude("xed-get-time.h");
    @cInclude("xed-iform-map.h");
    @cInclude("xed-ild.h");
    @cInclude("xed-immdis.h");
    @cInclude("xed-immed.h");
    @cInclude("xed-init.h");
    @cInclude("xed-inst.h");
    @cInclude("xed-interface.h");
    @cInclude("xed-isa-set.h");
    @cInclude("xed-operand-action.h");
    @cInclude("xed-operand-values-interface.h");
    @cInclude("xed-patch.h");
    @cInclude("xed-portability.h");
    @cInclude("xed-print-info.h");
    @cInclude("xed-reg-class.h");
    @cInclude("xed-rep-prefix.h");
    @cInclude("xed-state.h");
    @cInclude("xed-types.h");
    @cInclude("xed-util.h");
    @cInclude("xed-version.h");
    @cInclude("xed-address-width-enum.h");
    @cInclude("xed-attribute-enum.h");
    @cInclude("xed-build-defines.h");
    @cInclude("xed-category-enum.h");
    @cInclude("xed-chip-enum.h");
    @cInclude("xed-convert-table-init.h");
    @cInclude("xed-cpuid-group-enum.h");
    @cInclude("xed-cpuid-rec-enum.h");
    @cInclude("xed-encoder-gen-defs.h");
    @cInclude("xed-encoder-iforms.h");
    @cInclude("xed-error-enum.h");
    @cInclude("xed-exception-enum.h");
    @cInclude("xed-extension-enum.h");
    @cInclude("xed-flag-action-enum.h");
    @cInclude("xed-flag-enum.h");
    @cInclude("xed-gen-table-defs.h");
    @cInclude("xed-iclass-enum.h");
    @cInclude("xed-iform-enum.h");
    @cInclude("xed-iformfl-enum.h");
    @cInclude("xed-ild-enum.h");
    @cInclude("xed-init-pointer-names.h");
    @cInclude("xed-isa-set-enum.h");
    @cInclude("xed-machine-mode-enum.h");
    @cInclude("xed-mapu-enum.h");
    @cInclude("xed-nonterminal-enum.h");
    @cInclude("xed-operand-accessors.h");
    @cInclude("xed-operand-action-enum.h");
    @cInclude("xed-operand-convert-enum.h");
    @cInclude("xed-operand-ctype-enum.h");
    @cInclude("xed-operand-ctype-map.h");
    @cInclude("xed-operand-element-type-enum.h");
    @cInclude("xed-operand-element-xtype-enum.h");
    @cInclude("xed-operand-enum.h");
    @cInclude("xed-operand-storage.h");
    @cInclude("xed-operand-type-enum.h");
    @cInclude("xed-operand-visibility-enum.h");
    @cInclude("xed-operand-width-enum.h");
    @cInclude("xed-reg-class-enum.h");
    @cInclude("xed-reg-enum.h");
    @cInclude("xed-reg-role-enum.h");
    @cInclude("xed-syntax-enum.h");
});

pub usingnamespace C;
